[project]
name = "Crash Detect Plugin"
publisher = "pulsepm"
repo = "samp-plugin-crashdetect"
include_path = "include"

[resource.linux]
name = "^crashdetect-(.*)-linux.tar.gz$"
archive = true
includes = ["crashdetect-(.*)-linux"]
plugins = ["crashdetect-(.*)-linux/crashdetect.so"]

[resource.windows]
name = "^crashdetect-(.*)-win32.tar.gz$"
archive = true
includes = ["crashdetect-(.*)-win32"]
plugins = ["crashdetect-(.*)-win32/crashdetect.so"]

[runtime]
plugins = ["Zeex/samp-plugin-crashdetect"]

